routes/web.php
<?php

Route::get('/', 'HomeController')->name('home');
Route::post('logout', 'LogoutController')->name('logout');

Route::group(['middleware' => 'guest', 'as' => 'guest.'], function () {
    Route::post('register', 'RegistrationController')->name('register');
    Route::post('login', 'LoginController')->name('login');
    Route::group(['namespace' => 'Auth', 'as' => 'auth:', 'prefix' => 'auth'], function () {
        Route::get('facebook', 'FacebookController@redirectToProvider')->name('facebook');
        Route::get('facebook/callback', 'FacebookController@handleProviderCallback');
        Route::get('google', 'GoogleController@redirectToProvider')->name('google');;
        Route::get('google/callback', 'GoogleController@handleProviderCallback');
    });
});

Route::group(['as' => 'user.', 'namespace' => 'User', 'prefix' => 'user'], function () {
    Route::group(['middleware' => 'auth'], function () {
        Route::post('attraction/{attractionId}/review', 'ReviewController@submitReview')->name('review');
        Route::post('attraction/like', 'LikeAttractionController')->name('attraction.like');
        Route::get('profile', 'ProfileController')->name('profile');
        Route::patch('profile', 'ProfileController@update')->name('profile.update');
    });

    Route::resource('attraction', 'AttractionController');
});

Route::patch('review/{id}/status', 'User\ReviewController@setStatus')->name('review.set-status');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::group(['middleware' => 'role:admin'], function () {
        Route::get('/', 'DashboardController')->name('dashboard');
        Route::resource('user', 'UserController');
        Route::resource('attraction-category', 'AttractionCategoryController');
        Route::resource('attraction', 'AttractionController');
    });

    Route::group(['prefix' => 'attraction/{attraction}', 'as' => 'attraction.', 'middleware' => 'auth'], function () {
        Route::patch('accomodation', 'AccomodationController@update')->name('accomodation.update');
        Route::patch('transportation', 'TransportationController@update')->name('transportation.update');
        Route::patch('delicacy', 'DelicacyController@update')->name('delicacy.update');
        Route::patch('activity', 'ActivityController@update')->name('activity.update');
        Route::patch('photo', 'PhotoController@update')->name('photo.update');
    });
});

app/Attraction.php
<?php

namespace App;

use App\Accomodation;
use App\Activity;
use App\AttractionCategory;
use App\Delicacy;
use App\Photo;
use App\Rating;
use App\Tag;
use App\Transportation;
use App\User;
use DB;
use Illuminate\Database\Eloquent\Model;

class Attraction extends Model
{
    protected $fillable = [
        'user_id',
        'name',
        'description',
        'location',
        'latitude',
        'longitude',
        'festivities',
        'budget_range_min',
        'budget_range_max',
        'policy',
        'attraction_status',
        'status_remarks',
        'is_featured',
        'feature_banner',
    ];

    protected $appends = [
        'average_rating',
    ];

    protected $casts = [
        'is_featured' => 'boolean',
    ];

    public function accomodations()
    {
        return $this->hasMany(Accomodation::class);
    }

    public function delicacies()
    {
        return $this->hasMany(Delicacy::class);
    }

    public function transportations()
    {
        return $this->hasMany(Transportation::class);
    }

    public function categories()
    {
        return $this->belongsToMany(AttractionCategory::class, 'attraction_category', 'attraction_id', 'category_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function activities()
    {
        return $this->hasMany(Activity::class);
    }

    public function photos()
    {
        return $this->hasMany(Photo::class)
            ->orderBy('id');
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id')->withDefault(function ($owner) {
            $owner->firstname = 'N/A';
        });
    }

    public function scopeFieldsForMasterList($query)
    {
        return $query->orderBy('id', 'desc')->with(['categories']);
    }

    public function thumbnail()
    {
        return $this->hasOne(Photo::class)
            ->orderBy('id');
    }

    public function placeDummyPhoto()
    {
        return $this->photos->push(new Photo);
    }

    public function is($status)
    {
        return strtolower($status) === $this->attraction_status;
    }

    public function scopeOwnedBy($query, $userId)
    {
        return $query->whereUserId($userId);
    }

    public function isOwnedBy($userId)
    {
        return $this->user_id == $userId;
    }

    public function isNotOwnedBy($userId)
    {
        return !$this->isOwnedBy($userId);
    }

    public function scopeApproved($query)
    {
        return $query->whereAttractionStatus('approved');
    }

    public function scopeLikedBy($query, $userId)
    {
        return $query->whereHas('likers', function ($q) use ($userId) {
            return $q->whereUserId($userId);
        });
    }

    public function reviews()
    {
        return $this->hasMany(Rating::class, 'attraction_id');
    }

    public function approvedReviews()
    {
        return $this->reviews()->whereRatingStatus('approved');
    }

    public function pendingReviews()
    {
        return $this->reviews()->whereRatingStatus('pending');
    }

    public function getAverageRatingAttribute()
    {
        return $this->relationLoaded('approvedReviews') ? $this->approvedReviews->avg('rating') : 0;
    }

    public function likers()
    {
        return $this->belongsToMany(User::class, 'attraction_like', 'attraction_id', 'user_id');
    }

    public function isLikedBy($userId)
    {
        return $this->relationLoaded('likers')
        ? $this->likers->where('id', $userId)->first()
        : $this->likers()->where('users.id', $userId)->exists();
    }

    public static function scopeTop($query, $limit = 6)
    {
        $result = self::queryTop($limit);
        // dd($result->toArray());

        if ($result->isEmpty()) {
            return $query;
        }

        return $query->whereIn('id', $result->pluck('id'));
    }

    public function scopeNewest($query, $limit = 6)
    {
        return $query->approved()
            ->orderBy('id', 'desc')
            ->limit(6);
    }

    public static function queryTop($limit = 6)
    {
        $self = new static;

        return DB::table($self->getTable())
            ->select('attractions.id', DB::raw('IFNULL(AVG(ratings.rating), 0) AS average_rating'))
            ->whereAttractionStatus('approved')
            ->leftJoin('ratings', function ($join) {
                $join->on('ratings.attraction_id', '=', 'attractions.id')
                    ->whereRatingStatus('approved');
            })
            ->groupBy('attractions.id')
            ->orderBy('average_rating', 'desc')
            ->limit($limit)
            ->get();
    }

    public function scopeFeatured($query)
    {
        return $query->whereIsFeatured(1);
    }

    public function getFeatureBannerAttribute($value)
    {
        return $value ? asset("storage/{$value}") : null;
    }

    public function scopeForShowcase($query)
    {
        return $query->with([
            'photos',
            'categories',
            'tags',
            'approvedReviews',
            'likers',
        ]);
    }

    public function scopeWithTerm($query, $term)
    {
        return $query->where(function ($q) use ($term) {
            $q->where('name', 'like', "%{$term}%")->orWhere('description', 'like', "%{$term}%");
        })->orWhereHas('tags', function ($q) use ($term) {
            $q->where('description', 'like', "%{$term}%");
        });
    }

    public function scopeFeaturedFirst($query)
    {
        return $query->orderBy('is_featured', 'desc');
    }

    public function scopeNameLike($query, $value)
    {
        return $query->where('name', 'like', "%{$value}%");
    }

    public function scopeLocationLike($query, $value)
    {
        return $query->where('location', 'like', "%{$value}%");
    }

    public function scopeOfStatus($query, $value)
    {
        return $query->whereAttractionStatus($value);
    }

    public function scopeWithCategory($query, $categoryId)
    {
        return $query->whereHas('categories', function ($q) use ($categoryId) {
            $q->where('attraction_categories.id', '=', $categoryId);
        });
    }

    public function scopeWithPendingReviewsCount($query)
    {
        return $query->approved()->whereHas('pendingReviews')->withCount('pendingReviews');
    }
}

resources/views/admin/dashboard.blade.php
@extends('admin.layout')
@section('title', 'Admin Dashboard')

@section('body')
<div class="row">
    <div class="col-sm-6">
        <table class="table">
            <thead>
                <tr class="bg-success text-white">
                    <th>Attraction</th>
                    <th>Pending Reviews Count</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @forelse($attractionPendingReviews as $attraction)
                    <tr>
                        <td>{{ $attraction->name }}</td>
                        <td>{{ $attraction->pending_reviews_count }}</td>
                        <td>
                            <a href="{{ route('admin.attraction.edit', ['id' => $attraction->id, 'status' => 'pending']) }}#reviews" class="btn btn-info">Manage Reviews</a>
                        </td>
                    </tr>
                @empty
                <tr>
                    <td colspan="3" class="text-center">No pending reviews</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/admin/layout.blade.php
@extends('layouts.main')
@push('css')
<link rel="stylesheet" href="{{ asset('css/admin.css') }}">
@endpush

@section('content')
<nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
  <a class="navbar-brand" href="{{ route('admin.dashboard') }}">{{ config('app.name') }} ADMIN</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Logged in as : ADMIN
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link {{ Route::is('admin.dashboard') ? 'active' : '' }}" href="{{ route('admin.dashboard') }}">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {{ Route::is('admin.user.index') ? 'active' : '' }}" href="{{ route('admin.user.index') }}">Users </span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link {{ Route::is('admin.attraction.index') ? 'active' : '' }}" href="{{ route('admin.attraction.index') }}">Attractions</a>
            </li>

          </ul>
           <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link {{ Route::is('admin.attraction-category.index') ? 'active' : '' }}" href="{{ route('admin.attraction-category.index') }}">Attraction Categories</a>
            </li>
          </ul>
        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
            <h1 class="row mb-3">
                <div class="col">@yield('title')</div>

                <div class="col text-right">
                  @if(MyHelper::resourceMethodIn(['create', 'edit']))
                    <a href="{{ MyHelper::resource('index') }}" class="btn btn-primary"><i class="fas fa-chevron-left"></i> Back to list</a>
                  @elseif(MyHelper::resourceMethodIn(['index']))
                    <a href="{{ MyHelper::resource('create') }}" class="btn btn-primary"><i class="fas fa-plus"></i> New entry</a>
                  @endif
                </div>

            </h1>
          @yield('body')
        </main>
      </div>
    </div>
@endsection