routes/web.php
<?php

Route::get('/', 'HomeController')->name('home');
Route::post('logout', 'LogoutController')->name('logout');

Route::group(['middleware' => 'guest', 'as' => 'guest.'], function () {
    Route::post('register', 'RegistrationController')->name('register');
    Route::post('login', 'LoginController')->name('login');
    Route::group(['namespace' => 'Auth', 'as' => 'auth:', 'prefix' => 'auth'], function () {
        Route::get('facebook', 'FacebookController@redirectToProvider')->name('facebook');
        Route::get('facebook/callback', 'FacebookController@handleProviderCallback');
        Route::get('google', 'GoogleController@redirectToProvider')->name('google');;
        Route::get('google/callback', 'GoogleController@handleProviderCallback');
    });
});

Route::group(['as' => 'user.', 'namespace' => 'User', 'prefix' => 'user'], function () {
    Route::group(['middleware' => 'auth'], function () {
        Route::post('attraction/{attractionId}/review', 'ReviewController@submitReview')->name('review');
        Route::post('attraction/like', 'LikeAttractionController')->name('attraction.like');
        Route::get('profile', 'ProfileController')->name('profile');
        Route::patch('profile', 'ProfileController@update')->name('profile.update');
    });

    Route::resource('attraction', 'AttractionController');
});

Route::patch('review/{id}/status', 'User\ReviewController@setStatus')->name('review.set-status');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::group(['middleware' => 'role:admin'], function () {
        Route::get('/', 'DashboardController')->name('dashboard');
        Route::resource('user', 'UserController');
        Route::resource('attraction-category', 'AttractionCategoryController');
        Route::resource('attraction', 'AttractionController');
    });

    Route::group(['prefix' => 'attraction/{attraction}', 'as' => 'attraction.', 'middleware' => 'auth'], function () {
        Route::patch('accomodation', 'AccomodationController@update')->name('accomodation.update');
        Route::patch('transportation', 'TransportationController@update')->name('transportation.update');
        Route::patch('delicacy', 'DelicacyController@update')->name('delicacy.update');
        Route::patch('activity', 'ActivityController@update')->name('activity.update');
        Route::patch('photo', 'PhotoController@update')->name('photo.update');
    });
});

app/User.php
<?php

namespace App;

use App\Attraction;
use App\Rating;
use Hash;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'facebook_uid',
        'google_uid',
        'email',
        'username',
        'password',
        'firstname',
        'lastname',
        'gender',
        'contact_number',
        'address',
        'display_photo',
    ];

    protected $appends = [
        'fullname',
        'registration_method',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function scopeFieldsForMasterList($query)
    {
        return $query;
    }

    public function getFullNameAttribute()
    {
        return "{$this->firstname} {$this->lastname}";
    }

    public function setPasswordAttribute($val)
    {
        $this->attributes['password'] = Hash::make($val);
    }

    public function getRegistrationMethodAttribute()
    {
        if (is_null($this->facebook_uid) && is_null($this->google_uid)) {
            return 'ON SITE';
        }

        return is_null($this->facebook_uid) ? 'Google' : 'Facebook';
    }

    public function likedAttractions()
    {
        return $this->belongsToMany(Attraction::class, 'attraction_like', 'user_id', 'attraction_id')->select('attractions.id');
    }

    public function reviews()
    {
        return $this->hasMany(Rating::class);
    }

    public function lastReview(Attraction $attraction)
    {
        return $attraction->reviews()->givenBy($this->id)->latest()->first();
    }

    public function is($role)
    {
        return $role === $this->role;
    }

    public function isNot($role)
    {
        return !$this->is($role);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\CRUDController;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Session;

class UserController extends CRUDController
{
    public function __construct(User $model, Request $request)
    {
        parent::__construct();
        $this->resourceModel = $model;
        $this->validationRules = [
            'store' => [
                'firstname' => ['required'],
                'lastname' => ['required'],
                'contact_number' => ['required'],
                'address' => ['present'],
                'gender' => ['required', Rule::in(['male', 'female'])],
                'password' => 'required|min:6',
                'password_confirmation' => 'required|same:password',
                'email' => ['required', 'email', Rule::unique($model->getTable())],
                'username' => ['required', Rule::unique($model->getTable())],
            ],
            'update' => [
                'firstname' => ['required'],
                'lastname' => ['required'],
                'contact_number' => ['required'],
                'address' => ['present'],
                'gender' => ['required', Rule::in(['male', 'female'])],
                'password' => 'present|nullable|min:6',
                'password_confirmation' => 'present|nullable|same:password',
                'email' => ['required', 'email', Rule::unique($model->getTable())->ignore($request->route('user'))],
                'username' => ['required', Rule::unique($model->getTable())->ignore($request->route('user'))],
            ],
        ];
    }

    public function beforeIndex($query)
    {
        $request = request();

        $query->when(($name = $request->name), function ($query) use ($name) {
            return $query->whereRaw("CONCAT(firstname, ' ', lastname) LIKE '%{$name}%'");
        })->when(($email = $request->email), function ($query) use ($email) {
            return $query->where('email', '=', $email);
        });
    }

    public function beforeUpdate()
    {
        if (!trim(request()->password)) {
            unset($this->validatedInput['password']);
        }
    }

    public function afterStore($model)
    {
        Session::flash('growl', 'New user has been added.');
    }

    public function afterUpdate($model)
    {
        Session::flash('growl', 'User has been updated.');
    }
}

app/Http/Controllers/User/AttractionController.php
<?php

namespace App\Http\Controllers\User;

use App\Accomodation;
use App\Activity;
use App\Attraction;
use App\AttractionCategory;
use App\Delicacy;
use App\Http\Controllers\CRUDController;
use App\Photo;
use App\Tag;
use App\Transportation;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Session;

class AttractionController extends CRUDController
{
    public function __construct(
        Attraction $model,
        Request $request,
        AttractionCategory $category,
        Tag $tag
    ) {
        $this->middleware('auth', ['except' => 'show']);
        parent::__construct();
        $this->resourceModel = $model;
        $this->validationRules = [
            'store' => [
                'name' => ['required', Rule::unique($model->getTable())],
                'description' => ['required'],
                'location' => ['required'],
                'latitude' => ['required', 'numeric'],
                'longitude' => ['required', 'numeric'],
                'festivities' => ['present'],
                'policy' => ['present'],
                // 'attraction_status' => ['required', Rule::in(['pending', 'approved', 'rejected'])],
                'status_remarks' => ['sometimes'],
                'categories' => ['required', 'array'],
                // 'categories.*' => ['required', Rule::exists($category->getTable(), $category->getKeyName())],
                'tags' => ['present', 'nullable', 'array'],
                'budget_range_min' => ['required', 'numeric'],
                'budget_range_max' => ['required', 'numeric'],
            ],
            'update' => [
                'name' => ['required', Rule::unique($model->getTable())->ignore($request->route('attraction'))],
                'description' => ['required'],
                'location' => ['required'],
                'latitude' => ['required', 'numeric'],
                'longitude' => ['required', 'numeric'],
                'festivities' => ['present'],
                'policy' => ['present'],
                // 'attraction_status' => ['required', Rule::in(['pending', 'approved', 'rejected'])],
                'status_remarks' => ['sometimes'],
                'categories' => ['required', 'array'],
                // 'categories.*' => ['required', Rule::exists($category->getTable(), $category->getKeyName())],
                'tags' => ['present', 'nullable', 'array'],
                'budget_range_min' => ['required', 'numeric'],
                'budget_range_max' => ['required', 'numeric'],
            ],
        ];
    }

    public function beforeIndex($query)
    {
        $query->ownedBy(Auth::id())->with('photos');
    }

    public function beforeCreate()
    {
        $this->viewData['categoryList'] = AttractionCategory::pluck('description', 'description');
        $this->viewData['tagList'] = Tag::pluck('description', 'description');
    }

    public function beforeEdit($model)
    {
        $model->accomodations->when($model->accomodations->isEmpty(), function ($accomodations) {
            return $accomodations->push(new Accomodation);
        });
        $model->transportations->when($model->transportations->isEmpty(), function ($transportations) {
            return $transportations->push(new Transportation);
        });
        $model->delicacies->when($model->delicacies->isEmpty(), function ($delicacies) {
            return $delicacies->push(new Delicacy);
        });
        $model->activities->when($model->activities->isEmpty(), function ($activities) {
            return $activities->push(new Activity);
        });
        $model->photos->when($model->photos->count() < 5, function ($photos) use ($model) {
            $model->photos = $photos->pad(5, new Photo);
        });

        $reviewStatus = in_array(request()->review_status, ['pending', 'approved', 'rejected']) ? request()->review_status : 'pending';
        // dd($reviewStatus);
        $model->load(['reviews' => function ($query) use ($reviewStatus) {
            return $query->with('owner')->whereRatingStatus($reviewStatus);
        }]);
        $this->beforeCreate();
    }

    public function afterStore($attraction)
    {
        $tags = collect(request()->tags)->map(function ($item) {
            $tag = Tag::firstOrCreate(['description' => $item]);
            return $tag->id;
        });
        $categories = collect(request()->categories)->map(function ($item) {
            $category = AttractionCategory::firstOrCreate(['description' => $item]);
            return $category->id;
        });
        $attraction->categories()->attach($categories);
        $attraction->tags()->attach($tags);
        Session::flash('growl', 'Attraction successfully added. You can now manage the accomodations, transportation and more details.');
    }

    public function afterUpdate($attraction)
    {
        $tags = collect(request()->tags)->map(function ($item) {
            $tag = Tag::firstOrCreate(['description' => $item]);
            return $tag->id;
        });
        $categories = collect(request()->categories)->map(function ($item) {
            $category = AttractionCategory::firstOrCreate(['description' => $item]);
            return $category->id;
        });
        $attraction->categories()->sync($categories);
        $attraction->tags()->sync($tags);
        Session::flash('growl', 'Attraction successfully updated');
    }

    public function beforeStore()
    {
        $this->validatedInput['user_id'] = Auth::id();
        $this->validatedInput['attraction_status'] = 'pending';
    }

    public function beforeShow($attraction)
    {
        $attraction->load(['accomodations', 'activities', 'transportations', 'delicacies', 'owner', 'tags', 'photos', 'approvedReviews.owner']);
        $attraction->photos->when($attraction->photos->count() < 5, function ($photos) use ($attraction) {
            $attraction->photos = $photos->pad(5, new Photo);
        });
    }
}

app/Http/Controllers/User/LikeAttractionController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\Rule;

class LikeAttractionController extends Controller
{
    public function __invoke(Request $request)
    {
        $request->validate([
            'attraction_id' => ['required', Rule::exists('attractions', 'id')->where(function ($q) {
                return $q->whereAttractionStatus('approved');
            })],
        ]);

        $result = Auth::user()->likedAttractions()->toggle($request->attraction_id);

        return response()->json([
            'result' => true,
            'change' => empty($result['attached']) ? '-' : '+',
        ]);

    }
}

app/Http/Controllers/User/ProfileController.php
<?php

namespace App\Http\Controllers\User;

use App\Attraction;
use App\Http\Controllers\Controller;
use App\Rating;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Session;

class ProfileController extends Controller
{
    public function __invoke(Request $request)
    {
        $user = Auth::user();

        $favorites = Attraction::forShowcase()->likedBy($user->id)->paginate(5, ['*'], 'likes-page');
        $reviews = Rating::with('attraction')->givenBy($user->id)->paginate(5, ['*'], 'reviews-page');

        return view('user.profile', [
            'favorites' => $favorites,
            'reviews' => $reviews,
        ]);
    }

    public function update(Request $request)
    {
        $input = $request->validate([
            'firstname' => ['required'],
            'lastname' => ['required'],
            'contact_number' => ['required', 'digits:11'],
            'gender' => ['required', Rule::in(['male', 'female'])],
            'password' => 'nullable|min:6',
            'password_confirmation' => 'required_with:password|same:password',
            'email' => ['required', 'email', Rule::unique('users')->ignore(Auth::id())],
        ], [
            'firstname.required' => 'Required.',
            'lastname.required' => 'Required.',
            'contact_number.required' => 'Required.',
            'contact_number.digits' => 'Should have an exact length of 11 digits',
            'gender.required' => 'Required.',
            'password.required' => 'Required.',
            'password_confirmation.required' => 'Required.',
            'email.required' => 'Required.',
        ]);

        if (!$input['password']) {
            unset($input['password']);
        }

        Auth::user()->update($input);

        Session::flash('growl', 'Your profile has been successfully updated!');

        return response()->json([
            'result' => true,
        ]);
    }
}

app/Http/Controllers/User/ReviewController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Rating;
use Auth;
use Illuminate\Http\Request;

class ReviewController extends Controller
{
    public function submitReview($attractionId, Request $request)
    {
        $input = $request->validate([
            'rating' => 'required|int|min:1|max:5',
            'review' => 'sometimes',
        ]);

        $input['attraction_id'] = $attractionId;
        $input['user_id'] = Auth::id();

        Rating::create($input);

        return response()->json([
            'result' => true,
        ]);
    }

    public function setStatus($id, Request $request)
    {
        $request->validate([
            'review_status' => 'required|in:rejected,approved',
        ]);

        Rating::whereId($id)->update([
            'rating_status' => $request->review_status,
        ]);

        return response()->json([
            'result' => true,
        ]);
    }
}

resources/views/user/index.blade.php
@extends('admin.layout')
@section('title', 'Users')
@section('body')

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Full Name</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Address</th>
            <th>Contact Number</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @forelse($resourceList as $row)
        <tr>
            <td>{{ $row->fullname }}</td>
            <td>{{ $row->gender }}</td>
            <td>{{ $row->email}} <br> <small>Using: <span class="text-info">{{ $row->registration_method }}</span></small></td>
            <td>{{ $row->address }}</td>
            <td>{{ $row->contact_number }}</td>
            <td>
                @include('components.form.index-actions', ['id' => $row->id])
            </td>
        </tr>
        @empty
        <tr>
            <td colspan="6" class="text-danger text-center">Emtpty table</td>
        </tr>
        @endforelse
    </tbody>
</table>
@endsection

resources/views/user/manage.blade.php
@extends('admin.layout')
@section('title', 'Users')

@section('body')
@if(is_null($resourceData->id))
{!! Form::open(['url' => MyHelper::resource('store'), 'method' => 'POST']) !!}
@else
{!! Form::model($resourceData, ['url' => MyHelper::resource('update', ['id' => $resourceData->id]), 'method' => 'PATCH']) !!}
@endif

<div class="row">
    <div class="col-4">
        {!! Form::bsText('email', 'Email Address') !!}
        {!! Form::bsText('username', 'Username') !!}
        <div class="row">
            <div class="col">
                {!! Form::bsPassword('password', 'Desired Password') !!}
            </div>
            <div class="col">
                {!! Form::bsPassword('password_confirmation', 'Password, Again') !!}
            </div>
        </div>
    </div>
    <div class="col-5">
        <div class="row">
            <div class="col">
                {!! Form::bsText('firstname', 'First Name') !!}
            </div>
            <div class="col">
                {!! Form::bsText('lastname', 'Last Name') !!}
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                {!! Form::bsSelect('gender', 'Gender', ['' => '', 'male' => 'Male', 'female' => 'Female']) !!}
            </div>
            <div class="col">
                {!! Form::bsText('contact_number', 'Contact Number') !!}
            </div>
        </div>
        {!! Form::bsTextarea('address', 'Address', null, ['rows' => 4]) !!}
    </div>
</div>
<hr>
<button type="submit" class="btn btn-success">Save</button>

{!! Form::close() !!}
@endsection

resources/views/user/profile.blade.php
@extends('layouts.main')
@push('css')
<link rel="stylesheet" href="{{ asset('css/select2.min.css') }}">
<style>
    body{
        padding-top: 59px;
    }
   html, body,.container-fluid > .row:first-child {
        height: 100%;
   }
    .container-fluid {
        height: 100%;
    }
    .card.profile .form-group label{
        font-weight: bold;
        font-size: 13px;
        margin-bottom:2px;
    }
    .card.profile .form-group {
        margin-bottom: 7px;
    }
</style>
@endpush
@section('content')
    @include('main-navbar')
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="card profile mt-4">
                    <div class="card-body p-3">
                        {!! Form::model(auth()->user(), ['url' => route('user.profile.update'), 'method' => 'patch', 'class' => 'ajax']) !!}
                            {!! Form::bsText('username', 'Username', null, ['class' => 'form-control-plaintext', 'readonly' => true]) !!}
                            {!! Form::bsText('firstname', 'First Name', null, ['class' => 'form-control form-control-sm']) !!}
                            {!! Form::bsText('lastname', 'Last Name', null, ['class' => 'form-control form-control-sm']) !!}
                            {!! Form::bsText('email', 'Email Address', null, ['class' => 'form-control form-control-sm']) !!}
                            {!! Form::bsSelect('gender', 'Gender', ['' => '', 'male' => 'Male', 'female' => 'Female'], null, ['class' => 'custom-select custom-select-sm w-100']) !!}
                            {!! Form::bsText('contact_number', 'Contact Number', null, ['class' => 'form-control form-control-sm']) !!}
                            <hr>
                            {!! Form::bsPassword('password', 'Password', ['class' => 'form-control form-control-sm']) !!}
                            {!! Form::bsPassword('password_confirmation', 'Confirm Password', ['class' => 'form-control form-control-sm']) !!}
                            <hr>
                            <button type="submit" class="btn btn-success btn-block">Save</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
            <div class="col-sm-5">
                <h3 class="mt-4 pb-2">My Favorites {{ $favorites->total() ? "(".$favorites->total().")" : '' }}</h3>
                <ul class="list-unstyled">
                    @forelse($favorites as $item)
                        <li class="media mb-2 ">
                            <a href="{{ route('user.attraction.show', ['attraction' => $item->id]) }}">
                                <img class="mr-3 rounded" src="{{$item->thumbnail? $item->thumbnail->filepath : MyHelper::photoPlaceholder()}}" alt="{{ $item->name }}" style="height:80px; width: 80px;">
                            </a>
                            <div class="media-body  text-truncate">
                                <a href="{{ route('user.attraction.show', ['attraction' => $item->id]) }}">
                                    <h5 class="mt-0 mb-1">{{ $item->name }} </h5>
                                </a>
                                <p class="text-truncate mb-0">{{ $item->location }}</p>
                                 <span class="text-success">{{ $item->average_rating ?: 0 }} <i class="fas fa-star "></i> </span>
                            </div>
                        </li>
                    @empty
                    <p class="bg-warning p-3">No liked attractions.</p>
                    @endforelse
                </ul>
                {{ $favorites->links() }}
            </div>
            <div class="col-sm-4">
                <h3 class="mt-4 pb-2">My Reviews</h3>
                @forelse($reviews as $item)
                    <blockquote class="blockquoter">
                        <p class="mb-0 clearfix">
                            {!! $item->review ?: '<em class="text-danger">Empty</em> ' !!}
                            <small class="text-success float-right">{{ $item->rating ?: 0 }} <i class="fas fa-star"></i> </small>
                        </p>
                        <footer class="blockquote-footer">{{ $item->attraction->name }}, <cite>{{ date_create($item->created_at)->format('m/d/Y h:i a') }}</cite> </footer>
                    </blockquote>
                    <hr>
                 @empty
                <p class="bg-warning p-3">No reviews given</p>
                @endforelse
            </div>
        </div>
    </div>
@endsection