routes/web.php
<?php

Route::get('/', 'HomeController')->name('home');
Route::post('logout', 'LogoutController')->name('logout');

Route::group(['middleware' => 'guest', 'as' => 'guest.'], function () {
    Route::post('register', 'RegistrationController')->name('register');
    Route::post('login', 'LoginController')->name('login');
    Route::group(['namespace' => 'Auth', 'as' => 'auth:', 'prefix' => 'auth'], function () {
        Route::get('facebook', 'FacebookController@redirectToProvider')->name('facebook');
        Route::get('facebook/callback', 'FacebookController@handleProviderCallback');
        Route::get('google', 'GoogleController@redirectToProvider')->name('google');;
        Route::get('google/callback', 'GoogleController@handleProviderCallback');
    });
});

Route::group(['as' => 'user.', 'namespace' => 'User', 'prefix' => 'user'], function () {
    Route::group(['middleware' => 'auth'], function () {
        Route::post('attraction/{attractionId}/review', 'ReviewController@submitReview')->name('review');
        Route::post('attraction/like', 'LikeAttractionController')->name('attraction.like');
        Route::get('profile', 'ProfileController')->name('profile');
        Route::patch('profile', 'ProfileController@update')->name('profile.update');
    });

    Route::resource('attraction', 'AttractionController');
});

Route::patch('review/{id}/status', 'User\ReviewController@setStatus')->name('review.set-status');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::group(['middleware' => 'role:admin'], function () {
        Route::get('/', 'DashboardController')->name('dashboard');
        Route::resource('user', 'UserController');
        Route::resource('attraction-category', 'AttractionCategoryController');
        Route::resource('attraction', 'AttractionController');
    });

    Route::group(['prefix' => 'attraction/{attraction}', 'as' => 'attraction.', 'middleware' => 'auth'], function () {
        Route::patch('accomodation', 'AccomodationController@update')->name('accomodation.update');
        Route::patch('transportation', 'TransportationController@update')->name('transportation.update');
        Route::patch('delicacy', 'DelicacyController@update')->name('delicacy.update');
        Route::patch('activity', 'ActivityController@update')->name('activity.update');
        Route::patch('photo', 'PhotoController@update')->name('photo.update');
    });
});

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>2Cebu</title>
        <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/fontawesome-all.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/jquery.growl.css') }}">
        @stack('css')
    </head>
    <body>
        @yield('content')
        @stack('modals')
        <script type="text/javascript" src="{{ asset('js/jquery.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('js/jquery.growl.js') }}"></script>
        <script type="text/javascript" src="{{ asset('js/main.js') }}"></script>
        <script type="text/javascript">
            jQuery(document).ready(function($) {
                $('.like').click(function (e) {
                    e.preventDefault();
                    var $this  = $(this),
                        url = "{{ route('user.attraction.like') }}"
                    $.post(url, {
                        attraction_id: $this.data('pk'),
                    })
                    .done(function (res) {
                        if(res['result']){
                            var countEl = $this.find('.count'),
                             currentCount = parseInt(countEl.text());
                            res['change'] === '+' ? currentCount++ : currentCount--;

                            $('.count[data-pk='+$this.data('pk')+']').text(currentCount)
                                .closest('.like')
                                .toggleClass('text-dark');
                        }else{

                        }
                    })
                })
            });
        </script>
        @if(session('growl'))
            <script type="text/javascript">
                jQuery(document).ready(function($) {
                    $.growl.notice({ message: "{{ session('growl') }}", location: 'br', 'title': '', size: 'large' });
                });
            </script>
        @endif
        @stack('js')
    </body>
</html>